### ISSUE TITLE
FlightOffer: Too many follow-up requests: 21

### ISSUE THREAD

**Issue by pietrini** [pietrini/amadeus-android#7]
With this call, the client blocks the request with this error

https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=MAD&destinationLocationCode=MUC&departureDate=2020-04-02&adults=1

INFO: <-- HTTP FAILED: java.net.ProtocolException: Too many follow-up requests: 21

**Comment by pietrini** [comment]
Mar 03, 2020 11:33:26 PM okhttp3.internal.platform.Platform log
INFO: --> GET https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=MAD&destinationLocationCode=MUC&departureDate=2020-04-03&adults=1
Mar 03, 2020 11:33:26 PM okhttp3.internal.platform.Platform log
INFO: --> END GET
Mar 03, 2020 11:33:27 PM okhttp3.internal.platform.Platform log
INFO: <-- HTTP FAILED: java.net.ProtocolException: Too many follow-up requests: 21



java.net.ProtocolException: Too many follow-up requests: 21

	at |b|b|b(Coroutine boundary.|b(|b)
	at com.amadeus.android.shopping.FlightOffersSearch$get$2.invokeSuspend(FlightOffersSearch.kt:56)
	at com.amadeus.android.base.BaseApi$safeApiCall$2.invokeSuspend(BaseApi.kt:25)
	at com.amadeus.android.service.AmadeusTest$FlightOffers for origin and destination$1.invokeSuspend(AmadeusTest.kt:87)
Caused by: java.net.ProtocolException: Too many follow-up requests: 21
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:122)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at com.amadeus.android.token.AccessTokenInterceptor.intercept(AccessTokenInterceptor.kt:20)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:219)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by pietrini** [comment]
Fixed, issue with unauthorized api key and too much retry from authenticator
